# Generated by Django 5.1.1 on 2024-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_categoria_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.BigIntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
